# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b24dc7a2e3bf4d27c27264ad8ce252307730066212d02f9a8a8f020cf1e28693f0ad728011026a1718a634b679fb17fdd17df656e071e06dcc92e09f33ccb083

test:
  secret_key_base: 1e9bac819fff6d8ca8fb25a3a34f9d7a657f43fae131617faa65d60b4c7eea5980a5f43b4076b173926d3107140911494a604ae62194c82739c2771870b8e634

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
