- name: Install nginx
  apt: pkg=nginx state=latest

- name: Remove the default conf
  command: rm -rf /etc/nginx/sites-enabled/default

- name: Remove the app's symlink, if exists
  command: rm -rf /etc/nginx/sites-enabled/{{app_name}}

- name: Configure nginx for the app
  template: src=etc_nginx_sites-available_template.conf dest=/etc/nginx/sites-available/{{app_name}} group=www-data owner=www-data force=yes

- name: Enable the app
  command: ln -s /etc/nginx/sites-available/{{app_name}} /etc/nginx/sites-enabled/{{app_name}}

- name: Restart nginx
  action: service name=nginx state=restarted

