- name: Add puma-manager
  template: src=etc_init_puma-manager.conf dest=/etc/init/puma-manager.conf force=yes mode=0644
  tags: puma1

- name: Add puma config
  template: src=etc_puma.conf dest=/etc/puma.conf force=yes mode=0644

- name: Add puma init script
  template: src=etc_init_puma.conf dest=/etc/init/puma.conf force=yes mode=0644
  tags: puma2

- name: Add puma configuration
  template: src=puma_production.conf.rb dest={{ deploy_directory }}/shared/puma_production.rb group=deploy owner=deploy force=yes mode=0644

- name: Restart puma-manager
  action: service name=puma-manager state=restarted
